// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using apbd_kolos2.Data;

#nullable disable

namespace apbd_kolos2.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.5.24306.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("apbd_kolos2.Models.Backpacks", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.HasKey("CharacterId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("backpacks", (string)null);

                    b.HasData(
                        new
                        {
                            CharacterId = 1,
                            ItemId = 1,
                            Amount = 1
                        },
                        new
                        {
                            CharacterId = 2,
                            ItemId = 2,
                            Amount = 1
                        },
                        new
                        {
                            CharacterId = 3,
                            ItemId = 3,
                            Amount = 1
                        });
                });

            modelBuilder.Entity("apbd_kolos2.Models.Character_titles", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("TitleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AcquireAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CharacterId", "TitleId");

                    b.HasIndex("TitleId");

                    b.ToTable("character_titles", (string)null);

                    b.HasData(
                        new
                        {
                            CharacterId = 1,
                            TitleId = 1,
                            AcquireAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CharacterId = 2,
                            TitleId = 2,
                            AcquireAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CharacterId = 3,
                            TitleId = 3,
                            AcquireAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("apbd_kolos2.Models.Characters", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentWei")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("MaxWeight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("characters", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentWei = 1,
                            FirstName = "John1",
                            LastName = "Dough1",
                            MaxWeight = 10
                        },
                        new
                        {
                            Id = 2,
                            CurrentWei = 2,
                            FirstName = "John2",
                            LastName = "Dough2",
                            MaxWeight = 20
                        },
                        new
                        {
                            Id = 3,
                            CurrentWei = 3,
                            FirstName = "John3",
                            LastName = "Dough3",
                            MaxWeight = 30
                        });
                });

            modelBuilder.Entity("apbd_kolos2.Models.Items", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("items", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "John",
                            Weight = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ann",
                            Weight = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Jack",
                            Weight = 3
                        });
                });

            modelBuilder.Entity("apbd_kolos2.Models.Titles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("titles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "King1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "King2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "King3"
                        });
                });

            modelBuilder.Entity("apbd_kolos2.Models.Backpacks", b =>
                {
                    b.HasOne("apbd_kolos2.Models.Characters", "Character")
                        .WithMany("BackpacksCollection")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("apbd_kolos2.Models.Items", "Item")
                        .WithMany("BackpacksCollection")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("apbd_kolos2.Models.Character_titles", b =>
                {
                    b.HasOne("apbd_kolos2.Models.Characters", "Character")
                        .WithMany("CharacterTitlesCollection")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("apbd_kolos2.Models.Titles", "Title")
                        .WithMany("CharacterTitlesCollection")
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("apbd_kolos2.Models.Characters", b =>
                {
                    b.Navigation("BackpacksCollection");

                    b.Navigation("CharacterTitlesCollection");
                });

            modelBuilder.Entity("apbd_kolos2.Models.Items", b =>
                {
                    b.Navigation("BackpacksCollection");
                });

            modelBuilder.Entity("apbd_kolos2.Models.Titles", b =>
                {
                    b.Navigation("CharacterTitlesCollection");
                });
#pragma warning restore 612, 618
        }
    }
}
